// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: main.proto

package statproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DarkGRpc_GetHealth_FullMethodName                 = "/statproto.DarkGRpc/GetHealth"
	DarkGRpc_GetBases_FullMethodName                  = "/statproto.DarkGRpc/GetBases"
	DarkGRpc_GetBasesMarketGoods_FullMethodName       = "/statproto.DarkGRpc/GetBasesMarketGoods"
	DarkGRpc_GetCommodities_FullMethodName            = "/statproto.DarkGRpc/GetCommodities"
	DarkGRpc_GetCommoditiesMarketGoods_FullMethodName = "/statproto.DarkGRpc/GetCommoditiesMarketGoods"
	DarkGRpc_GetAmmos_FullMethodName                  = "/statproto.DarkGRpc/GetAmmos"
	DarkGRpc_GetAmmosMarketGoods_FullMethodName       = "/statproto.DarkGRpc/GetAmmosMarketGoods"
	DarkGRpc_GetAmmosTechCompat_FullMethodName        = "/statproto.DarkGRpc/GetAmmosTechCompat"
)

// DarkGRpcClient is the client API for DarkGRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeter service definition.
type DarkGRpcClient interface {
	// Sends a greeting
	GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	GetBases(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBasesReply, error)
	GetBasesMarketGoods(ctx context.Context, in *GetMarketGoodsInput, opts ...grpc.CallOption) (*GetMarketGoodsReply, error)
	GetCommodities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCommoditiesReply, error)
	GetCommoditiesMarketGoods(ctx context.Context, in *GetMarketGoodsInput, opts ...grpc.CallOption) (*GetMarketGoodsReply, error)
	GetAmmos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAmmoReply, error)
	GetAmmosMarketGoods(ctx context.Context, in *GetMarketGoodsInput, opts ...grpc.CallOption) (*GetMarketGoodsReply, error)
	GetAmmosTechCompat(ctx context.Context, in *GetTechCompatInput, opts ...grpc.CallOption) (*GetTechCompatReply, error)
}

type darkGRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewDarkGRpcClient(cc grpc.ClientConnInterface) DarkGRpcClient {
	return &darkGRpcClient{cc}
}

func (c *darkGRpcClient) GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetBases(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBasesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBasesReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetBasesMarketGoods(ctx context.Context, in *GetMarketGoodsInput, opts ...grpc.CallOption) (*GetMarketGoodsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketGoodsReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetBasesMarketGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetCommodities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCommoditiesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommoditiesReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetCommodities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetCommoditiesMarketGoods(ctx context.Context, in *GetMarketGoodsInput, opts ...grpc.CallOption) (*GetMarketGoodsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketGoodsReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetCommoditiesMarketGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetAmmos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAmmoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAmmoReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetAmmos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetAmmosMarketGoods(ctx context.Context, in *GetMarketGoodsInput, opts ...grpc.CallOption) (*GetMarketGoodsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketGoodsReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetAmmosMarketGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkGRpcClient) GetAmmosTechCompat(ctx context.Context, in *GetTechCompatInput, opts ...grpc.CallOption) (*GetTechCompatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTechCompatReply)
	err := c.cc.Invoke(ctx, DarkGRpc_GetAmmosTechCompat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DarkGRpcServer is the server API for DarkGRpc service.
// All implementations must embed UnimplementedDarkGRpcServer
// for forward compatibility.
//
// The greeter service definition.
type DarkGRpcServer interface {
	// Sends a greeting
	GetHealth(context.Context, *Empty) (*HealthReply, error)
	GetBases(context.Context, *Empty) (*GetBasesReply, error)
	GetBasesMarketGoods(context.Context, *GetMarketGoodsInput) (*GetMarketGoodsReply, error)
	GetCommodities(context.Context, *Empty) (*GetCommoditiesReply, error)
	GetCommoditiesMarketGoods(context.Context, *GetMarketGoodsInput) (*GetMarketGoodsReply, error)
	GetAmmos(context.Context, *Empty) (*GetAmmoReply, error)
	GetAmmosMarketGoods(context.Context, *GetMarketGoodsInput) (*GetMarketGoodsReply, error)
	GetAmmosTechCompat(context.Context, *GetTechCompatInput) (*GetTechCompatReply, error)
	mustEmbedUnimplementedDarkGRpcServer()
}

// UnimplementedDarkGRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDarkGRpcServer struct{}

func (UnimplementedDarkGRpcServer) GetHealth(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedDarkGRpcServer) GetBases(context.Context, *Empty) (*GetBasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBases not implemented")
}
func (UnimplementedDarkGRpcServer) GetBasesMarketGoods(context.Context, *GetMarketGoodsInput) (*GetMarketGoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasesMarketGoods not implemented")
}
func (UnimplementedDarkGRpcServer) GetCommodities(context.Context, *Empty) (*GetCommoditiesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommodities not implemented")
}
func (UnimplementedDarkGRpcServer) GetCommoditiesMarketGoods(context.Context, *GetMarketGoodsInput) (*GetMarketGoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommoditiesMarketGoods not implemented")
}
func (UnimplementedDarkGRpcServer) GetAmmos(context.Context, *Empty) (*GetAmmoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmmos not implemented")
}
func (UnimplementedDarkGRpcServer) GetAmmosMarketGoods(context.Context, *GetMarketGoodsInput) (*GetMarketGoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmmosMarketGoods not implemented")
}
func (UnimplementedDarkGRpcServer) GetAmmosTechCompat(context.Context, *GetTechCompatInput) (*GetTechCompatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmmosTechCompat not implemented")
}
func (UnimplementedDarkGRpcServer) mustEmbedUnimplementedDarkGRpcServer() {}
func (UnimplementedDarkGRpcServer) testEmbeddedByValue()                  {}

// UnsafeDarkGRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DarkGRpcServer will
// result in compilation errors.
type UnsafeDarkGRpcServer interface {
	mustEmbedUnimplementedDarkGRpcServer()
}

func RegisterDarkGRpcServer(s grpc.ServiceRegistrar, srv DarkGRpcServer) {
	// If the following call pancis, it indicates UnimplementedDarkGRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DarkGRpc_ServiceDesc, srv)
}

func _DarkGRpc_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetBases(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetBasesMarketGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketGoodsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetBasesMarketGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetBasesMarketGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetBasesMarketGoods(ctx, req.(*GetMarketGoodsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetCommodities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetCommodities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetCommodities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetCommodities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetCommoditiesMarketGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketGoodsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetCommoditiesMarketGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetCommoditiesMarketGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetCommoditiesMarketGoods(ctx, req.(*GetMarketGoodsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetAmmos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetAmmos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetAmmos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetAmmos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetAmmosMarketGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketGoodsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetAmmosMarketGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetAmmosMarketGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetAmmosMarketGoods(ctx, req.(*GetMarketGoodsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkGRpc_GetAmmosTechCompat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechCompatInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkGRpcServer).GetAmmosTechCompat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarkGRpc_GetAmmosTechCompat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkGRpcServer).GetAmmosTechCompat(ctx, req.(*GetTechCompatInput))
	}
	return interceptor(ctx, in, info, handler)
}

// DarkGRpc_ServiceDesc is the grpc.ServiceDesc for DarkGRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DarkGRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statproto.DarkGRpc",
	HandlerType: (*DarkGRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _DarkGRpc_GetHealth_Handler,
		},
		{
			MethodName: "GetBases",
			Handler:    _DarkGRpc_GetBases_Handler,
		},
		{
			MethodName: "GetBasesMarketGoods",
			Handler:    _DarkGRpc_GetBasesMarketGoods_Handler,
		},
		{
			MethodName: "GetCommodities",
			Handler:    _DarkGRpc_GetCommodities_Handler,
		},
		{
			MethodName: "GetCommoditiesMarketGoods",
			Handler:    _DarkGRpc_GetCommoditiesMarketGoods_Handler,
		},
		{
			MethodName: "GetAmmos",
			Handler:    _DarkGRpc_GetAmmos_Handler,
		},
		{
			MethodName: "GetAmmosMarketGoods",
			Handler:    _DarkGRpc_GetAmmosMarketGoods_Handler,
		},
		{
			MethodName: "GetAmmosTechCompat",
			Handler:    _DarkGRpc_GetAmmosTechCompat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
