version: "2"
linters:
  disable:
    - staticcheck
    - ineffassign
  settings:
    errcheck:
      exclude-functions:
        - encoding/binary.Read
        - encoding/binary.Write
    govet:
      disable:
        - structtag
        - unreachable
    staticcheck:
      checks:
        - "all"
        - "-QF1005"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1023"
  exclusions:
    rules:
      - path: darkmap/front/static_front/scripts/
        linters:
          - errcheck
      - path: darkmap/dds/dds_test.go
        linters:
          - errcheck
      - path: darkmap/tga/
        linters:
          - errcheck
      - path: darkmap/utfextract/script/
        linters:
          - errcheck
