version: "3"

tasks:
  test:
    cmds:
      - task: build-version
      - go test ./... -coverprofile=cover.out {{.CLI_ARGS}}
    vars:
      PWD:
        sh: echo '$(pwd)'

  test:cover:
    cmds:
      - task: build-version
      - go tool cover -html=cover.out

  test:cover:total:
    cmds:
      - task: build-version
      - task: test
      - go tool cover -func cover.out

  build:
    cmds:
      - task: build-version
      - templ generate
      - go run . build

  web:
    cmds:
      - task: build-version
      - templ generate
      # - task: swag:build
      - go run . web

  dev:templ:
    cmds:
      - task: build-version
      - templ generate -watch --cmd="go run . web"

  dev:watch:
    cmds:
      - task: build-version
      # pip install watchdog[watchmedo]
      - >
        ~/venv/bin/watchmedo auto-restart 
        --patterns "*.templ;*.go;*.css;*.js;enverant.json" 
        -i "*_templ.go"
        --recursive
        -- sh -c "task web; sleep infinity"

  build:test:
    cmds:
      - task: build-version
      - mkdir -p dist
      - rm dist/darkstat-linux-amd64 | true
      - GOOS=linux GOARCH=amd64 go build -v -o dist/darkstat-linux-amd64 main.go

  build-version:
    cmds:
      - autogit semver --publish > darkstat/settings/version.txt || echo 'v0.0.0' > darkstat/settings/version.txt

  build:bins:
    cmds:
      - task: build-version
      - mkdir -p dist
      - rm dist/* | true

      - GOOS=linux GOARCH=amd64 go build -v -o dist/darkstat-linux-amd64 main.go
      - GOOS=linux GOARCH=arm64 go build -v -o dist/darkstat-linux-arm64 main.go
      - GOOS=windows GOARCH=amd64 go build -v -o dist/darkstat-windows-amd64.exe main.go
      - GOOS=windows GOARCH=arm64 go build -v -o dist/darkstat-windows-arm64.exe main.go
      - GOOS=darwin GOARCH=amd64 go build -v -o dist/darkstat-macos-amd64 main.go
      - GOOS=darwin GOARCH=arm64 go build -v -o dist/darkstat-macos-arm64 main.go

      # We can build for those too, but i don't think they are needed
      # - GOOS=linux GOARCH=386 go build -v -o dist/darkstat-linux-386 main.go
      # - GOOS=linux GOARCH=arm go build -v -o dist/darkstat-linux-arm main.go
      # - GOOS=windows GOARCH=386 go build -v -o dist/darkstat-windows-386.exe main.go
      # - GOOS=windows GOARCH=arm go build -v -o dist/darkstat-windows-arm.exe main.go

  hook:prod:
    cmds:
      - sudo rm /usr/local/bin/darkstat | true
      - GOOS=linux GOARCH=amd64 go build -v -o dist/darkstat-linux-amd64 main.go
      - sudo ln -s {{.PWD}}/dist/darkstat-linux-amd64 /usr/local/bin/darkstat

  docker:build:
    cmds:
      - docker build --build-arg "BUILD_VERSION=$tag_version" --tag darkwind8/darkstat:$tag_version .

  docker:push:
    cmds:
      - docker push darkwind8/darkstat:$tag_version
      - docker tag darkwind8/darkstat:$tag_version darkwind8/darkstat:staging
      - docker push darkwind8/darkstat:staging
      - docker pull darkwind8/darkstat:staging && docker service update --image darkwind8/darkstat:staging darkstat-staging

  docker:run:
    cmds:
      - docker run -it darkwind8/darkstat:$tag_version

  docker:deploy:
    cmds:
      - docker tag darkwind8/darkstat:staging darkwind8/darkstat:production
      - docker push darkwind8/darkstat:production
      - docker pull darkwind8/darkstat:production && docker service update --image darkwind8/darkstat:production darkstat-production

  kcl:build:
    cmds:
      - kcl kcls/build.k

  swag:build:
    cmds:
      - rm docs/docs.go | true
      - swag init --parseDependency

  profiler:cpu:
    cmds:
      - go tool pprof main.go prof.prof

  profiler:mem: # https://www.codingexplorations.com/blog/memory-management-and-profiling-in-go
    cmds:
      - go tool pprof mem.pprof

  profiler:web:
    cmds:
      # https://www.codereliant.io/memory-leaks-with-pprof/
      - go tool pprof -alloc_space http://localhost:6060/debug/pprof/heap
      # commands like `top`, `web`, `list FunctionName`

env:
  tag_version: v1.48.0-a4
  DOCKER_HOST: ssh://root@darklab:22
  # DARKCORE_PASSWORD: "1233"
  # DARKCORE_SECRET: "passphrasewgichneedstobe32bytes!"
  # RELAY_HOST: "darkrelay.mydd84ai.com:8080"
