# Generated by Django 3.1.7 on 2021-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='cruise_speed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
