# Generated by Django 3.1.7 on 2021-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_ship_cruise_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='impulse_speed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
