# Generated by Django 3.1.7 on 2021-04-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_ship_impulse_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ship',
            name='camera_angular_acceleration',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='camera_horizontal_turn_angle',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='camera_turn_look_ahead_slerp_amount',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='camera_vertical_turn_down_angle',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='camera_vertical_turn_up_angle',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='explosion_resistance',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='hit_pts',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='hold_size',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ids_info',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='linear_drag',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='max_bank_angle',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='nudge_force',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='strafe_force',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='strafe_power_usage',
        ),
        migrations.CreateModel(
            name='Ship1',
            fields=[
                ('ship1_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('linear_drag', models.FloatField(blank=True, null=True)),
                ('camera_angular_acceleration', models.FloatField(blank=True, null=True, verbose_name='ang speed')),
                ('camera_turn_look_ahead_slerp_amount', models.FloatField(blank=True, null=True, verbose_name='look ahead')),
                ('nudge_force', models.FloatField(blank=True, null=True)),
                ('explosion_resistance', models.FloatField(blank=True, null=True, verbose_name='exp res')),
            ],
            bases=('ship.piece',),
        ),
        migrations.CreateModel(
            name='Ship2',
            fields=[
                ('ship2_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('ids_info', models.IntegerField(blank=True, db_index=True, null=True)),
                ('hold_size', models.IntegerField(blank=True, null=True)),
                ('max_bank_angle', models.IntegerField(blank=True, db_index=True, null=True)),
                ('camera_horizontal_turn_angle', models.IntegerField(blank=True, null=True, verbose_name='hor ang')),
                ('camera_vertical_turn_up_angle', models.IntegerField(blank=True, null=True, verbose_name='turn up')),
                ('camera_vertical_turn_down_angle', models.IntegerField(blank=True, null=True, verbose_name='turn down')),
                ('hit_pts', models.IntegerField(blank=True, null=True)),
                ('strafe_force', models.IntegerField(blank=True, null=True)),
                ('strafe_power_usage', models.IntegerField(blank=True, null=True, verbose_name='strafe usage')),
            ],
            bases=('ship.piece',),
        ),
        migrations.AddField(
            model_name='ship',
            name='ship1_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.ship1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='ship2_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ship.ship2'),
            preserve_default=False,
        ),
    ]
