# Generated by Django 3.1.7 on 2021-04-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_auto_20210426_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipIntegers',
            fields=[
                ('ship_integer_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('ids_info', models.IntegerField(blank=True, db_index=True, null=True)),
                ('hold_size', models.IntegerField(blank=True, null=True)),
                ('max_bank_angle', models.IntegerField(blank=True, db_index=True, null=True)),
                ('camera_horizontal_turn_angle', models.IntegerField(blank=True, null=True, verbose_name='hor ang')),
                ('camera_vertical_turn_up_angle', models.IntegerField(blank=True, null=True, verbose_name='turn up')),
                ('camera_vertical_turn_down_angle', models.IntegerField(blank=True, null=True, verbose_name='turn down')),
                ('hit_pts', models.IntegerField(blank=True, null=True)),
                ('strafe_force', models.IntegerField(blank=True, null=True)),
                ('strafe_power_usage', models.IntegerField(blank=True, null=True, verbose_name='strafe usage')),
                ('ids_info1', models.IntegerField(blank=True, null=True)),
                ('ids_info2', models.IntegerField(blank=True, null=True)),
                ('ids_info3', models.IntegerField(blank=True, null=True)),
                ('ship_class', models.IntegerField(blank=True, null=True)),
                ('nanobot_limit', models.IntegerField(blank=True, null=True, verbose_name='nanobots')),
                ('shield_battery_limit', models.IntegerField(blank=True, null=True, verbose_name='batteries')),
            ],
            bases=('ship.piece',),
        ),
        migrations.CreateModel(
            name='ShipSpecial',
            fields=[
                ('ship_special_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('ids_name', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('typeof', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('info_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, default=None, null=True)),
                ('charge_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('cruise_speed', models.IntegerField(blank=True, default=None, null=True)),
                ('impulse_speed', models.IntegerField(blank=True, default=None, null=True)),
            ],
            bases=('ship.piece',),
        ),
        migrations.RenameModel(
            old_name='Ship1',
            new_name='ShipStrFloats',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='ship1_ptr',
            new_name='shipstrfloats_ptr',
        ),
        migrations.RenameField(
            model_name='shipstrfloats',
            old_name='ship1_piece',
            new_name='ship_float_piece',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='charge_rate',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='cruise_speed',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ids_info1',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ids_info2',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ids_info3',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ids_name',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='impulse_speed',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='info_name',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='nanobot_limit',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='shield_battery_limit',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ship2_ptr',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ship_class',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='typeof',
        ),
        migrations.DeleteModel(
            name='Ship2',
        ),
        migrations.AddField(
            model_name='ship',
            name='shipintegers_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ship.shipintegers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='shipspecial_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ship.shipspecial'),
            preserve_default=False,
        ),
    ]
