# Generated by Django 3.1.7 on 2021-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_ship_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='charge_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
