# Generated by Django 3.1.7 on 2021-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_auto_20210411_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='capacity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='charge_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
