"""
Django settings for fldarknet project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import secrets
import os
from dotenv import load_dotenv

basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(basedir, ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
ROOT_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("debug") in ['True', 'true']


class ConfigPaths:
    "file paths"

    def __init__(self):
        self.freelancer_path = os.environ.get(
            "freelancer_folder")

        self.data_dir = os.path.join(self.freelancer_path, "DATA")

        self.equipment_dir = os.path.join(self.data_dir, "EQUIPMENT")
        self.service_dir = os.path.join(self.freelancer_path, "SERVICE")
        self.infocards_path = os.path.join(self.service_dir, "infocards.txt")
        self.universe_dir = os.path.join(self.data_dir, "UNIVERSE")
        self.ships_dir = os.path.join(self.data_dir, "SHIPS")


PATHS = ConfigPaths()

# in seconds
TIMEOUT_BETWEEN_PARSE = int(os.environ.get("timeout") or '1000')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY") or secrets.token_hex(32)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "parsing.apps.ParsingConfig",
    "main.apps.MainConfig",
    "ship.apps.ShipConfig",
    "commodity.apps.CommodityConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'django_celery_beat',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(ROOT_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ROOT_DIR / 'db.sqlite3',
    }, "memory": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "file:memdb1?mode=memory&cache=shared",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

DJANGO_PASSWORD_VALIDAION = "django.contrib.auth.password_validation."
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": DJANGO_PASSWORD_VALIDAION + "UserAttributeSimilarityValidator",
    },
    {
        "NAME": DJANGO_PASSWORD_VALIDAION + "MinimumLengthValidator",
    },
    {
        "NAME": DJANGO_PASSWORD_VALIDAION + "CommonPasswordValidator",
    },
    {
        "NAME": DJANGO_PASSWORD_VALIDAION + "NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"


# Celery Configuration Options
CELERY_TIMEZONE = "Australia/Tasmania"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

DJANGO_CELERY_BEAT_TZ_AWARE = False
