# Generated by Django 3.1.7 on 2021-04-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('loot_appearance', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('pod_appearance', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('ids_info', models.IntegerField(blank=True, db_index=True, null=True)),
                ('units_per_container', models.IntegerField(blank=True, db_index=True, null=True)),
                ('decay_per_second', models.IntegerField(blank=True, null=True)),
                ('hit_pts', models.IntegerField(blank=True, null=True)),
                ('ids_name', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'commodities',
            },
        ),
    ]
