# Generated by Django 3.1.7 on 2021-04-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShipIntegers',
            fields=[
                ('ship_integer_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('ids_info', models.IntegerField(blank=True, db_index=True, null=True)),
                ('hold_size', models.IntegerField(blank=True, null=True)),
                ('max_bank_angle', models.IntegerField(blank=True, db_index=True, null=True)),
                ('camera_horizontal_turn_angle', models.IntegerField(blank=True, null=True, verbose_name='hor ang')),
                ('camera_vertical_turn_up_angle', models.IntegerField(blank=True, null=True, verbose_name='turn up')),
                ('camera_vertical_turn_down_angle', models.IntegerField(blank=True, null=True, verbose_name='turn down')),
                ('hit_pts', models.IntegerField(blank=True, null=True)),
                ('strafe_force', models.IntegerField(blank=True, null=True)),
                ('strafe_power_usage', models.IntegerField(blank=True, null=True, verbose_name='strafe usage')),
                ('ids_info1', models.IntegerField(blank=True, null=True)),
                ('ids_info2', models.IntegerField(blank=True, null=True)),
                ('ids_info3', models.IntegerField(blank=True, null=True)),
                ('ship_class', models.IntegerField(blank=True, null=True)),
                ('nanobot_limit', models.IntegerField(blank=True, null=True, verbose_name='nanobots')),
                ('shield_battery_limit', models.IntegerField(blank=True, null=True, verbose_name='batteries')),
            ],
            bases=('ship.piece',),
        ),
        migrations.CreateModel(
            name='ShipSpecial',
            fields=[
                ('ship_special_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('ids_name', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('typeof', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('info_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, default=None, null=True)),
                ('charge_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('cruise_speed', models.IntegerField(blank=True, default=None, null=True)),
                ('impulse_speed', models.IntegerField(blank=True, default=None, null=True)),
            ],
            bases=('ship.piece',),
        ),
        migrations.CreateModel(
            name='ShipStrFloats',
            fields=[
                ('ship_float_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.piece')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('linear_drag', models.FloatField(blank=True, null=True)),
                ('camera_angular_acceleration', models.FloatField(blank=True, null=True, verbose_name='ang speed')),
                ('camera_turn_look_ahead_slerp_amount', models.FloatField(blank=True, null=True, verbose_name='look ahead')),
                ('nudge_force', models.FloatField(blank=True, null=True)),
                ('explosion_resistance', models.FloatField(blank=True, null=True, verbose_name='exp res')),
            ],
            bases=('ship.piece',),
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('shipspecial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ship.shipspecial')),
                ('shipintegers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ship.shipintegers')),
                ('shipstrfloats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ship.shipstrfloats')),
            ],
            options={
                'verbose_name_plural': 'ships',
            },
            bases=('ship.shipstrfloats', 'ship.shipintegers', 'ship.shipspecial'),
        ),
    ]
