{
 "title": "App Darkstat",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(darkstat_build_info,environment)"
    }
   },
   { "name": "interval", "query": "2m,5m,10m,30m,1h,6h" }
  ]
 },
 "panels": [
  { "title": "Http Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "darkstat_uptime_seconds{environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(darkstat_http_by_ip_finished_total{environment=~\"$environment\"}[$interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Succesful By Ip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(darkstat_http_by_ip_finished_total{status_code=~\"2.*|3.*\", environment=~\"$environment\", ip!=\"127.0.0.1\"}[$interval])) by (status_code, ip)",
     "legendFormat": "user - {{status_code}}"
    }
   ]
  },
  {
   "title": "Finished Failed By Ip",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_ip_finished_total{status_code=~\"4.*|5.*\", environment=~\"$environment\"}) by (status_code, ip)",
     "legendFormat": "user - {{status_code}}"
    }
   ]
  },
  {
   "title": "Unique IPs in a 1 day",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count (present_over_time(darkstat_http_by_ip_finished_total{environment=~\"$environment\"}[1d])) by (ip))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished by Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(darkstat_http_by_pattern_duration_seconds_hist_count{environment=~\"$environment\"}[$interval])) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Failed by Pattern (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_duration_seconds_hist_count{status_code=~\"4.*|5.*\",environment=~\"$environment\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Average Execution By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_sum{environment=~\"$environment\"}[$interval])) /\nsum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_count{environment=~\"$environment\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Loading Time By Pattern",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (darkstat_http_by_pattern_duration_seconds_hist_sum{environment=~\"$environment\"})\n\n",
     "legendFormat": "{{pattern}}:{{status_code}}"
    }
   ]
  },
  {
   "title": "P50 Http Execution By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(darkstat_http_by_pattern_duration_seconds_hist_bucket{environment=~\"$environment\"}[5m]))  by (status_code, pattern, environment, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 execution by pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(darkstat_http_by_pattern_duration_seconds_hist_bucket{environment=~\"$environment\"}[5m]))  by (status_code, pattern, environment, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 execution by pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(darkstat_http_by_pattern_duration_seconds_hist_bucket{environment=~\"$environment\"}[5m]))  by (status_code, pattern, environment, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Average Execution By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_sum{pattern!=\"index.html\", environment=~\"$environment\"}[$interval])) /\nsum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_count{pattern!=\"index.html\", environment=~\"$environment\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50-P75-P90 latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(darkstat_http_by_pattern_duration_seconds_hist_bucket{environment=~\"$environment\"}[$interval])) by (status_code, environment, le)) ",
     "legendFormat": "P50 {{environment}}, {{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(darkstat_http_by_pattern_duration_seconds_hist_bucket{environment=~\"$environment\"}[$interval])) by (status_code, environment, le)) ",
     "legendFormat": "P70 {{environment}}, {{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(darkstat_http_by_pattern_duration_seconds_hist_bucket{environment=~\"$environment\"}[$interval])) by (status_code, environment, le)) ",
     "legendFormat": "P90 {{environment}}, {{status_code}}"
    }
   ]
  },
  {
   "title": "Http Body Size P50 pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(darkstat_http_by_pattern_body_size_bytes_hist_bucket{environment=~\"$environment\"}[5m]))  by (status_code, pattern, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Body Size Sum Load By pattern (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (increase(darkstat_http_by_pattern_body_size_bytes_hist_sum{environment=~\"$environment\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Average Body Size By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (increase(darkstat_http_by_pattern_body_size_bytes_hist_sum{environment=~\"$environment\"}[$interval])) /\nsum by(status_code, pattern) (increase(darkstat_http_by_pattern_body_size_bytes_hist_count{environment=~\"$environment\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load By Status Code and Env",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (status_code, environment) (increase(darkstat_http_by_pattern_duration_seconds_hist_sum{environment=~\"$environment\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Body Size Sum Load By pattern (1h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (increase(darkstat_http_by_pattern_body_size_bytes_hist_sum{environment=~\"$environment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load By Pattern Rate in 2m",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pattern, environment) (increase(darkstat_http_by_pattern_duration_seconds_hist_sum{environment=~\"$environment\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Api Usages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Grpc Called Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(grpc_method) (grpc_server_msg_sent_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grpc API Gateway Called Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_duration_seconds_hist_count{environment=~\"$environment\", pattern=~\"/statproto.*\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http API Called Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_duration_seconds_hist_count{environment=~\"$environment\", pattern=~\"/api.*\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http API Called Total useragents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_useragent_finished_total{environment=~\"$environment\", pattern=~\"/api.*\"}) by (pattern, useragent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grpc Called Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(grpc_method) (grpc_server_msg_sent_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grpc API Gatway Called Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_duration_seconds_hist_count{environment=~\"$environment\", pattern=~\"/statproto.*\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http API Called Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_duration_seconds_hist_count{environment=~\"$environment\", pattern=~\"/api.*\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http API Called Total useragents",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_useragent_finished_total{environment=~\"$environment\", pattern=~\"/api.*\"}) by (useragent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http API Called Total useragents by logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"production-darkstat-app\"} | json | url_pattern=~\"/api.*\" | user_agent!=\"Go-http-client/2.0\" [2m])) by (user_agent)"
    }
   ]
  },
  {
   "title": "Http API Called Total useragents by logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"production-darkstat-app\"} | json | __error__=\"\" | url_pattern=~\"/api.*\" | user_agent!=\"\" | user_agent!=\"Go-http-client/1.1\" [2h])) by (user_agent)"
    }
   ]
  }
 ]
}