package urls

import (
	"github.com/darklab8/go-utils/utils/utils_types"
)

const (
	Docs utils_types.FilePath = "docs.html"

	Index            utils_types.FilePath = "index.html"
	DarkIndex        utils_types.FilePath = "dark.html"
	VanillaIndex     utils_types.FilePath = "vanilla.html"
	LightIndex       utils_types.FilePath = "light.html"
	Bases            utils_types.FilePath = "stat/bases.html"
	TradesFrom       utils_types.FilePath = "stat/trades_from.html"
	TradesTo         utils_types.FilePath = "stat/trades_to.html"
	TradeDeals       utils_types.FilePath = "stat/trade_deals.html"
	Asteroids        utils_types.FilePath = "stat/asteroids.html"
	TravelRoutes     utils_types.FilePath = "stat/travel_routes.html"
	Missions         utils_types.FilePath = "stat/missions.html"
	Factions         utils_types.FilePath = "stat/factions.html"
	Bribes           utils_types.FilePath = "stat/bribes.html"
	Commodities      utils_types.FilePath = "stat/commodities.html"
	Guns             utils_types.FilePath = "stat/guns.html"
	GunModifiers     utils_types.FilePath = "stat/gun_modifiers.html"
	Ammo             utils_types.FilePath = "stat/ammo.html"
	Swagger          utils_types.FilePath = "swagger"
	Missiles         utils_types.FilePath = "stat/missiles.html"
	Mines            utils_types.FilePath = "stat/mines.html"
	Shields          utils_types.FilePath = "stat/shields.html"
	Thrusters        utils_types.FilePath = "stat/thrusters.html"
	Ships            utils_types.FilePath = "stat/ships.html"
	ShipDetails      utils_types.FilePath = "stat/ship_details.html"
	Tractors         utils_types.FilePath = "stat/tractors.html"
	IDRephacks       utils_types.FilePath = "stat/id_rephacks.html"
	Engines          utils_types.FilePath = "stat/engines.html"
	CounterMeasures  utils_types.FilePath = "stat/counter_measures.html"
	ExtraItems       utils_types.FilePath = "stat/extra_items.html"
	Scanners         utils_types.FilePath = "stat/scanners.html"
	PoBs             utils_types.FilePath = "stat/pobs.html"
	PoBGoods         utils_types.FilePath = "stat/pob_goods.html"
	TwoWayDeals      utils_types.FilePath = "stat/two_way_deals.html"
	LootableUnlocked utils_types.FilePath = "stat/lootable_unlocked.html"
	Lootablelocked   utils_types.FilePath = "stat/lootable_locked.html"
	Craftable        utils_types.FilePath = "stat/craftable.html"
)
