package urls

import (
	"github.com/darklab8/go-utils/utils/utils_types"
)

const (
	Docs utils_types.FilePath = "docs.html"

	Index               utils_types.FilePath = "index.html"
	DarkLightIndex      utils_types.FilePath = "darklight.html"
	DarkIndex           utils_types.FilePath = "dark.html"
	VanillaIndex        utils_types.FilePath = "vanilla.html"
	LightIndex          utils_types.FilePath = "light.html"
	Bases               utils_types.FilePath = "st/bases.html"
	TradesFrom          utils_types.FilePath = "st/trades_from.html"
	TradesTo            utils_types.FilePath = "st/trades_to.html"
	TradeDeals          utils_types.FilePath = "st/trade_deals.html"
	Asteroids           utils_types.FilePath = "st/asteroids.html"
	AsteroidsWithCrafts utils_types.FilePath = "st/asteroids_with_crafts.html"
	TravelRoutes        utils_types.FilePath = "st/travel_routes.html"
	Missions            utils_types.FilePath = "st/missions.html"
	Factions            utils_types.FilePath = "st/factions.html"
	Bribes              utils_types.FilePath = "st/bribes.html"
	Commodities         utils_types.FilePath = "st/commodities.html"
	Guns                utils_types.FilePath = "st/guns.html"
	GunModifiers        utils_types.FilePath = "st/gun_modifiers.html"
	Ammo                utils_types.FilePath = "st/ammo.html"
	Swagger             utils_types.FilePath = "swagger"
	Missiles            utils_types.FilePath = "st/missiles.html"
	Mines               utils_types.FilePath = "st/mines.html"
	Shields             utils_types.FilePath = "st/shields.html"
	Thrusters           utils_types.FilePath = "st/thrusters.html"
	Ships               utils_types.FilePath = "st/ships.html"
	ShipDetails         utils_types.FilePath = "st/ship_details.html"
	Tractors            utils_types.FilePath = "st/tractors.html"
	IDRephacks          utils_types.FilePath = "st/id_rephacks.html"
	Engines             utils_types.FilePath = "st/engines.html"
	CounterMeasures     utils_types.FilePath = "st/cms.html"
	ExtraItems          utils_types.FilePath = "st/extra_items.html"
	Scanners            utils_types.FilePath = "st/scanners.html"
	PoBs                utils_types.FilePath = "st/pobs.html"
	PoBGoods            utils_types.FilePath = "st/pob_goods.html"
	TwoWayDeals         utils_types.FilePath = "st/two_way_deals.html"
	LootableUnlocked    utils_types.FilePath = "st/lootable_unlocked.html"
	Lootablelocked      utils_types.FilePath = "st/lootable_locked.html"
	Craftable           utils_types.FilePath = "st/craftable.html"
)
