# Generated by Django 3.1.7 on 2021-03-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='HP_bay_external',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='HP_bay_surface',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='HP_tractor_source',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='bay_door_anim',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='bay_doors_close_snd',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='bay_doors_open_snd',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='destructible',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='loadout',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='nomad',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='phantom_physics',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='shape_name',
        ),
    ]
