# Generated by Django 3.1.7 on 2021-03-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_auto_20210323_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='camera_angular_acceleration',
            field=models.FloatField(blank=True, null=True, verbose_name='ang speed'),
        ),
    ]
