name: Test Protoc Regen

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    name: Test Docker
    steps:
    - uses: actions/checkout@v3
    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master
    - name: Set up Go
      uses: darklab8/infra/.github/actions/install-go@master
    - name: Install Templ
      uses: darklab8/infra/.github/actions/install-templ@master
    - name: generate Templ files
      run: templ generate
    - name: Install Swag
      uses: darklab8/infra/.github/actions/install-swag@master
    - name: Build swag go stuff
      run: swag init --parseDependency
    - name: add versions
      run: task build-version
    - name: Test Docker building and regenerating files
      run: task grpc:docker:gateway
    - name: Check if there are differences
      run: git diff
