# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test Configs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        freelancer-mod:
          - "discovery"
          - "vanilla"
    name: Test ${{ matrix.freelancer-mod }}
    steps:
    - uses: actions/checkout@v3
    - uses: darklab8/infra/.github/actions/checkout-freelancer@master
      with:
        freelancer-mod: "${{ matrix.freelancer-mod }}"
        freelancer-folder: '${{ github.workspace }}/${{ matrix.freelancer-mod }}'
    - run: ls ./${{ matrix.freelancer-mod }}
    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master
    - name: Set up Go
      uses: darklab8/infra/.github/actions/install-go@master
    - name: Install Templ
      uses: darklab8/infra/.github/actions/install-templ@master
    - name: generate Templ files
      run: templ generate
    - name: Install Swag
      uses: darklab8/infra/.github/actions/install-swag@master
    - name: Build swag go stuff
      run: swag init --parseDependency
    - name: add versions
      run: task build-version
    - name: Test
      run: go test ./...
      env:
        # CONFIGS_LOG_LEVEL: "DEBUG"
        CONFIGS_FREELANCER_FOLDER: ${{ github.workspace }}/${{ matrix.freelancer-mod }}
