name: Test build
'on':
  push:
    branches:
    - master
  schedule:
  - cron: '0 9 * * *'
  pull_request: {}
jobs:
  job:
    name: Test build
    runs-on: ubuntu-22.04
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Checkout Freelancer
      uses: darklab8/infra/.github/actions/checkout-freelancer@master
      with:
        freelancer-mod: discovery
        freelancer-folder: ${{ github.workspace }}/fl-data
    - run: ls ./fl-data
    - name: Install Go
      uses: darklab8/infra/.github/actions/install-go@master
    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master
    - name: Install Templ
      uses: darklab8/infra/.github/actions/install-templ@master
    - name: generate Templ files
      run: templ generate
    - name: Install Swag
      uses: darklab8/infra/.github/actions/install-swag@master
    - name: Build swag go stuff
      run: swag init --parseDependency
    - name: add versions
      run: task build-version
    - name: Patch freelancer discovery to latest
      uses: darklab8/infra/.github/actions/patch-disco@master
      with:
        freelancer-folder: ${{ github.workspace }}/fl-data
    - name: Test things
      run: task test
      env:
        CONFIGS_FREELANCER_FOLDER: ${{ github.workspace }}/fl-data
    - name: build
      run: task build
      env:
        DARKSTAT_SITE_HOST: ''
        DARKSTAT_SITE_ROOT: /fl-darkstat/
        CONFIGS_FREELANCER_FOLDER: ${{ github.workspace }}/fl-data
        DARKSTAT_FLDARKSTAT_HEADING: <span style="font-weight:1000;">DEV ENV</span> <a href="https://github.com/darklab8/fl-darkstat">fl-darkstat</a> for <a href="https://github.com/darklab8/fl-data-discovery">Freelancer Discovery</a>
        DARKSTAT_RELAY_HOST: https://darkrelay-staging.dd84ai.com
