# Generated by Django 3.1.7 on 2021-03-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=50)),
                ('ids_name', models.IntegerField(db_index=True)),
                ('ids_info', models.IntegerField(db_index=True)),
                ('lootable', models.BooleanField()),
                ('decay_per_second', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'commodities',
            },
        ),
    ]
