# Generated by Django 3.1.7 on 2021-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
