# Generated by Django 3.1.7 on 2021-03-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_commodity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='decay_per_second',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='ids_info',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='ids_name',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='lootable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
