# Generated by Django 3.1.7 on 2021-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_auto_20210321_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='lootable',
        ),
        migrations.AddField(
            model_name='commodity',
            name='hit_pts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='infocard',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='loot_appearance',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='units_per_container',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
