# Generated by Django 3.1.7 on 2021-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0004_auto_20210321_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='pod_appearance',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
